### ISSUE TITLE
Alignment issues

### ISSUE THREAD

**Issue by zymox** [DeadlyCrush/DeadlyTrade#1]
A lot of the overlays etc seem misaligned. See screenshot for 2 examples (but this effects everything else too): 

- Syndicate Overlay is cut off at Tora (this is max zoomed). 
- Currency overlay has a horizontal scrollbar

Probably resolution related? I'm running on 2560x1440, windowed fullscreen

![screen](https://user-images.githubusercontent.com/18327640/74604434-46335900-50be-11ea-8b77-f6985ccb1b59.png)

**Comment by DeadlyCrush** [comment]
If u installed gulim font.
I guess I missed something related with resolution.
I will check that and fix it. Thank you for your detailed report.

**Comment by DeadlyCrush** [comment]
Fixed. Will testing other resolution.

[DeadlyTrade Next Version][Release Plan Changed]
1.4.0.1 version that modified, fixed bug, added new functions. Release plan was this week. But plan is changed.

1. I guess does not much means realease at end of the league
2. We decided to release of the 1.4.0.1 release in the season break, which is work in progress my major plan and priority. Because the release is more meaningful before and after the season break.

I will guide again on the detailed progress and deployment plan of the above.

Thank you always Exile~!
