### ISSUE TITLE
Trade whispe options not save

### ISSUE THREAD

**Issue by fragfaq** [DeadlyCrush/DeadlyTrade#2]
Can't save this option. Other saved. [Video](https://gfycat.com/sphericalpreciousbighornedsheep).

**Comment by DeadlyCrush** [comment]
Thanks your for your report.
Whisper options save at json file.
I missed that apply to UI instantly. Thanks again.

**Comment by DeadlyCrush** [comment]
Fixed.

[DeadlyTrade Next Version][Release Plan Changed]
1.4.0.1 version that modified, fixed bug, added new functions. Release plan was this week. But plan is changed.

1. I guess does not much means realease at end of the league
2. We decided to release of the 1.4.0.1 release in the season break, which is work in progress my major plan and priority. Because the release is more meaningful before and after the season break.

I will guide again on the detailed progress and deployment plan of the above.

Thank you always Exile~!
