### ISSUE TITLE
Recursive "can't set hotkeys" window and crash

### ISSUE THREAD

**Issue by tfp** [DeadlyCrush/DeadlyTrade#20]
App crashed after a flicker show of the "can't set hotkey" window.
That was after I configured the emergency key to CTRL+# on my german keyboard, what got displayed as "CONTROL;OEMQuestion". This worked to set, but after a restart of the app it could not set the hotkey anymore.
Tested again: after reload it's "CONTROL;OEMQUESTION" - so you uppercased it somewhere, causing the initial problem.
If you then access DeadlyTrade outside of PoE active, e.g. while browsing and this error comes up, chances are high it crashes with recursive/infinite tries.

**Comment by DeadlyCrush** [comment]
Thanks you for your report @tfp 
I guess you use gaming gear keyboard or some kind of not normal keyboard. KeyCode OEM~ is not setting in DeadlyTrade.
I will check that KeyCode and share the progress here.

* I will release update version. refer to below notice please.
[DeadlyTrade Next Version][Release Plan Changed]
1.4.0.1 version that modified, fixed bug, added new functions. Release plan was this week. But plan is changed.

1. I guess does not much means realease at end of the league
2. We decided to release of the 1.4.0.1 release in the season break, which is work in progress my major plan and priority. Because the release is more meaningful before and after the season break.

I will guide again on the detailed progress and deployment plan of the above.

Thank you always Exile~!

**Comment by tfp** [comment]
No, I don't use a special gaming keyboard.
OEM-Keys is how windows identifies language/country-specific keys. So this should be a common issue if someone wants to change keybindings.
See https://docs.microsoft.com/de-de/dotnet/api/system.windows.forms.keys?view=netframework-4.8

**Comment by DeadlyCrush** [comment]
1st Update 1.4.0.1
Rework (Trade Notification, ChatScan, Settings, UI) + a few new useful features. + bug fix. + stablized. 
→ 2020.03.10~2020.03.11 (local time in Korea) 

2nd Update 1.4.0.2
Add price check related main features like trademacro and currenycop. 
→ 2020.03.13~2020.03.14 (local time in Korea)

**Comment by DeadlyCrush** [comment]
=======================
1.4.0.3 DeadlyTrade Released.

○ CONFIG File is changed.
- Sorry, CONFIG File is changed for BUG Fix.

○ BUG FIX
- Fixed Labyrinth Overlay Zoomin, Zoomout, Close Button Action
- Fixed Moving stash tab by CTRL+MouseWheel
- Fixed Trade Notification Pop-up
- Fixed Korean Trade Message Parsing
. Korean trade whisper changed that cause trade message parsing bug.
. Korean trade whisper's a few default words was changed. ex) 을(를) to (을)를
- Fixed Cache File Cleaner : ShaderCacheD3D11 & ShaderCacheD3D11_GI
- Fixed Save Configuration in Settings.
